apiVersion: v1
kind: Service
metadata:
    name: karsajobs-backend
    labels:
        app: karsajobs-backend
spec:
    type: NodePort
    selector:
        app: karsajobs-backend
    ports:
        - port: 8080
          nodePort: 30001
