apiVersion: v1
kind: Service
metadata:
    name: karsajobs-ui
    labels:
        app: karsajobs-ui
spec:
    type: NodePort
    selector:
        app: karsajobs-ui
    ports:
        - port: 8000
          nodePort: 30002
